In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='Visadataset.csv'
visa_df=pd.read_csv(path)

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [27]:
# check how many unique values available
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [8]:
# create a dictionary assign a number start with zero
# for each lables based on alphabetical order 
Dict={'Certified':0,'Denied':1}
Dict

{'Certified': 0, 'Denied': 1}

In [9]:
visa_df['case_status'].map(Dict)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [12]:
# map the dictnory with columns
visa_df['case_status']=visa_df['case_status'].map(Dict)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,NaN
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,NaN
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,NaN
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,NaN
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,NaN
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,NaN
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,NaN
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,NaN
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,NaN

In [13]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [15]:
Dict1={'Asia':0, 'Africa':1, 'North America':2, 'Europe':3, 'South America':4,
       'Oceania':5}
Dict1

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [16]:
visa_df['continent'].map(Dict1)

0        0
1        0
2        0
3        0
4        1
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: continent, Length: 25480, dtype: int64

In [17]:
visa_df['continent']=visa_df['continent'].map(Dict1)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,NaN
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,NaN
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,NaN
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,NaN
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,NaN
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,NaN
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,NaN
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,NaN
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,NaN

In [29]:
labels=visa_df['continent'].unique()
d={}
for i in range(len(labels)):
    key=labels[i]
    d[key]=i
d={labels[i]:i for i in range(len(labels))}   # i labels[i]
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [30]:
# using dict comprehension 
d={labels[i]:i for i in range(len(labels))}   # i labels[i]
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [35]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)
for i in cat:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}   # i labels[i]
    visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**Label Encoder**

- package name: **sklearn**

    - class: **preprocessing**
        
            - method: **LabelEncoder**

from sklearn.preprocessing import LabelEncoder

In [ ]:
- step-1: import the method

- step-2: save the method

- step-3: apply the fit transform 


**fit transform**

- fit : find some thing 
    - first we are finding dictionary 
- transform : change the data 
    - using the dictionary we are changing Eng to Number

In [36]:
from sklearn.preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)

le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0])

In [37]:
from sklearn.preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)
le=LabelEncoder()
for i in cat:
    le.fit_transform(visa_df[i])

## OneHotEncoder

- The method name is: pd.get_dummies

|case_status|case_status_Denied|case_status_Certified|
|-|-|-|
|Denied|1|0|
|Certified|0|1|

In [41]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)

pd.get_dummies(visa_df['continent'],
              dtype='int')

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

LabelEncoder vs OneHotEncoder

- Generally we dont want a relation between input columns
- we need both aput columns are not correlated each other
- we need both input columns are **independent(X,Y)** each other
- we need both input columns are **perpendicular** each other
- we need both input columns are **Orthogonal** each other
- we need both input columns are **90 degrees phase shift** each other
- OneHotEncoder will achieve above
- But OneHotEncoder creates new columns
    - columns are incraese means dimensions are incresae
    - More dimension data need more processing time
    - More dimension data need more infra
    - This is called **Curse of Dimensioanlly**