In [1]:
import numpy as np 
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Mumbai',np.nan,'Delhi']}
df=pd.DataFrame(Data)
df

     Names   Age    City
0   Ramesh   NaN    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0     NaN
3      NaN  27.0   Delhi

In [3]:
import numpy as np 
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',None],
     'Age':[None,22,25,27],
     'City':['Pune','Mumbai',None,'Delhi']}
df1=pd.DataFrame(Data)
df1

     Names   Age    City
0   Ramesh   NaN    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0    None
3     None  27.0   Delhi

In [4]:
import numpy as np 
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',Null],
     'Age':[Null,22,25,27],
     'City':['Pune','Mumbai',Null,'Delhi']}
df2=pd.DataFrame(Data)
df2
# only np.nan and None consider as a none values

NameError: name 'Null' is not defined

In [5]:
df.to_csv('Missing_Values.csv',index=False)

In [11]:
df1.to_csv('Missing_Values1.csv',index=False)

In [8]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [12]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [13]:
df.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [14]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [15]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

## fillna

In [45]:
#df.fillna(30)

In [46]:
#df['Age'].fillna(30,inplace=True)
df

     Names   Age    City
0   Ramesh  30.0    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0    None
3     None  27.0   Delhi

- the above one is we are filling randomly 
- all the columns are filled with random numbers 
- It is not good approch because in a data we have different datatypes

In [48]:
df.fillna('Hyd')

     Names   Age    City
0   Ramesh  30.0    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0     Hyd
3      Hyd  27.0   Delhi

**What is the diffrent btw np.nan and none**

In [25]:
np.nan+5

nan

In [26]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [27]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [28]:
arr1

array([ 1.,  2., nan,  3.])

In [29]:
arr2

array([1, 2, None, 3], dtype=object)

In [30]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [31]:
np.sum(arr2)
# None is very dangeous for the

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represent float type
- None represent Object type
- if data operations related to Maths then nan format is better

**Fill the value based on column**

In [32]:
# df.fillna()
df['Names'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

**Fill with Method**

- Whever we are using methods no need to provide values

In [33]:
import numpy as np
import pandas as pd

-pad

-bfill

-ffill

-backfill

In [43]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)
# fills the above values

     Names   Age    City
0   Ramesh  30.0    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0    25.0
3     None  27.0   Delhi

In [42]:
df.fillna(method='bfill')

     Names   Age    City
0   Ramesh  30.0    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0   Delhi
3     None  27.0   Delhi

In [49]:
df.fillna(method='ffill')

     Names   Age    City
0   Ramesh  30.0    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0  Mumbai
3  Sathish  27.0   Delhi

In [50]:
df.fillna(method='backfill')

     Names   Age    City
0   Ramesh  30.0    Pune
1   Suresh  22.0  Mumbai
2  Sathish  25.0   Delhi
3     None  27.0   Delhi

**Mean--Median--Mode**

- instead of filling with random values

- we can use mean median and mode also 

- For Numerical columns use mean and Median 

    - if Data outliers are there use Median 
- For categorical columns use Mode

In [52]:
# First calculate median 
# Then fill with median
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [53]:
age_median

26.0

In [61]:
mode=df['City'].mode()
mode

0     Delhi
1    Mumbai
2      Pune
Name: City, dtype: object

**KNN Immpter**

    - K-Nearest Neighbours
    - Where k= hyper parameters which means the user can change
    - Idea: instead of taking all the samples 
        - First fix the neighbours number i.e. k
        - Then find the neighnours using distance metric 
        - Then take the average of those samples to fill the missing value

In [5]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [6]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X = [[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [ ]:
# import method 
# save method 
# fit tranform

In [7]:
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,
                    weights='uniform')
imputer.fit_transform(X)

# 8+3/2=5.5
# 60+2/2=31
# 7+3/2=5   2 is the neighbour

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [ ]:
================= EDA Steps =======================
# interview question : Tell me about the EDA steps 
1. Read the data 
2. separate categorical columns and numerical Columns
3. Data quick checks shape, columns, dtypes, 
4. Null 
5. Do some data preprocess if any column is corrupted 
    ex: Numerical values in categorical clumns 
    ex: Categorical values in numerical columns 
6. Drop the Id type columns which means a Data has unique labels 
    Drop the Single value columns
7. Categorical column analysis 
        a) Frequency table 
        b) Bar charts
        c) Pie charts 
8. Numerical Column Anlysis 
        a) Histrogram
        b) Distribustion 
        c) Box plot 
9. Outlier analysis
    Impute the outliers with Median 
10. FInd the correlation Between numerical columns 
    Heat map
11. Convert cat to Numerical 
    A) LabelEncoder 
    B) One Hot Encoder 
12. Scale the data 
    A) Z standardization
    B) Normaization

by performing 12 steps, we achieve 3 things 
(i) Cleaned data
(ii) Data in the form of complete Numerical 
(iii) we have some understanding the data 

13. we will try to select the important feature fro ML model 
    A) PCA : principle component anlaysis (will be covered in ML)

Finally we achieve 3 data sets 

1. Till step-11:
    with out scale but data in Numerical format 
2. Till step-12:
    with scaling data in Numerical format 
3. Till step-13:
    PCA data