================== Data Analysis ====================

1. Pandas              : Data frame analysis
2. Numpy               : Numerical analysis
3. matplotlib          : Graphs and plots
4. seaborn             : plots
5. Bokhe               : plots
6. plotly              : plots


================== Machine Learning =================

7. stats                 : for statistical models
8. scikit-learn(sklearn) : ML models

================== Deep Learning ===================

9.opencv                : Computer vision
10.pillow               : Image operations
11.Tensor Flow          : Neural Network creations (developed by google)
12.keras                : NN
13. pytorch             : alternative package of tensorflow (fackbook meta)

================= NLP ================================

14. NLTK                 : Natural language toolkit
15. Spacy                : Alternative to NLTK
16. wordcloud            : most frequent occured words 

===================Scrapping ==========================

17. SqLite               : Data base creation 
18. Beautiful soup
19. Seleium

====================API creation ===========================

20.Flask
21.FastAPI
22.Gradio
23.Django

===================== UI app creations =======================

24. Streamlit

=====================Transfer learning models (DL)=======================

25.Mobilenet
26.Resnet
27.VGGnet
28.Inception
29.Yolo                : Ultralytics

===================== Transfer learning models(NLP)=======================

30. Word2vec
31. GloVe

=======================Huging Face Transformation ========================

32. Allen NLP packages

======================== GenAI ====================================

34. LangChain
35. Google GeminiAi realted Packages
36. OpenAI GPT realted Packages
37. Amazon BedRock realted packages
38. Meta Lama realted packages

======================== Image and Video Generations ======================

39. GAN models related packages
40. SORA related packages

============================ Model development (Mlops) ===================

41. mlflow using databricks 
42. kubeflow (GCP account)

============================= Cloud applictions =====================

43. Azure ML realted packages
44. GCP VertexAI 
45. AWS Sagemaker realted packages

================================= Small ===============================

46. time 
47. logging
48. math
49. random
50. env

**Step :1 Import packages**

In [6]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

**Step :2 Create a data frame using list**

- data

- index

- columns

In [7]:
#names=['Ramesh','Suresh','Satish']
#pd.DataFrame(names,
#             columns=['names'])
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
            columns=['names'])

    names
0  Ramesh
1  Suresh
2  Satish

**Step 3: Change the index**

In [8]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
             index=['i','ii','iii'],
             columns=['names'])


# fruits=['Jackfruit','Mango','Jamun']
# pd.DataFrame(fruits,
#            index=['a','b','c'],
#            columns=['fruits'])

      names
i    Ramesh
ii   Suresh
iii  Satish

In [5]:
names=['Ramesh','Suresh','Satish']
idx=['A','B','C']
col=['names']
pd.DataFrame(names,idx,col)

    names
A  Ramesh
B  Suresh
C  Satish

**Step 4: Add multiplty columns**

In [9]:
names=['Ramesh','Suresh','Satish']
age=[10,20,30]
pd.DataFrame(zip(names,age),columns=['names','age'])

    names  age
0  Ramesh   10
1  Suresh   20
2  Satish   30

In [7]:
np.__version__

'2.1.3'

**Step-5: Create emplty dataframe and update the columns**

In [9]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [10]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Mahesh']
df['Age']=['10','20','30']
df

    Names Age
0  Ramesh  10
1  Suresh  20
2  Mahesh  30

**Step-6 : Add a new column with existing dataframe**

In [11]:
names=['Ramesh','Suresh','Satish']
age=[10,20,30]
df=pd.DataFrame(zip(names,age),
                columns=['names','age'])
df['Gender']=['M','M','M']
df

    names  age Gender
0  Ramesh   10      M
1  Suresh   20      M
2  Satish   30      M

**Step-7: Overwrite the column**

In [12]:
df['Age']=[30,40,50]
df
# if we change the small 'a' to 'A' then it will create the new column

    names  age Gender  Age
0  Ramesh   10      M   30
1  Suresh   20      M   40
2  Satish   30      M   50

**Step-8: Drop the column**

- lables

- axis

- index

- columns

- inplace

In [13]:
df.drop('age')   # error
# here python asssume age is a label 
# python ask qn : is it index label or column label 
# axis =1 means for columns
# axis =0 means for rows
# by defaults axis=0

In [30]:
df.drop('age',axis=0)   # error
# even 0 also it will take error

KeyError: "['age'] not found in axis"

In [13]:
df.drop('Age',axis=1)

    names  age Gender
0  Ramesh   10      M
1  Suresh   20      M
2  Satish   30      M

In [14]:
df
# we are able to see old coulmn 
# because we did not apply inplace =True

    names  age Gender  Age
0  Ramesh   10      M   30
1  Suresh   20      M   40
2  Satish   30      M   50

In [15]:
df.drop(columns=['Age'],inplace=True)

In [16]:
df

    names  age Gender
0  Ramesh   10      M
1  Suresh   20      M
2  Satish   30      M

In [46]:
df.drop(index=2,
       axis=0)
# drop the index 2

    names  age Gender
0  Ramesh   30      M
1  Suresh   40      M

**Step-9 : Remane the col**

In [ ]:
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | None' = None,
    inplace: 'bool' = False,
    level: 'Level | None' = None,
    errors: 'IgnoreRaise' = 'ignore',
) -> 'DataFrame | None'

In [17]:
name=['jatin','praneeth','amit']
age=['10','20','30']
city=['MP','JK','DEl']
pd.DataFrame(zip(name,age,city),
            columns=['Name','Age','City'])
#df.rename()

       Name Age City
0     jatin  10   MP
1  praneeth  20   JK
2      amit  30  DEl

In [18]:
# direct call the list
dict_name={'age':'AGE'}
df.rename(columns=dict_name)

    names  AGE Gender
0  Ramesh   10      M
1  Suresh   20      M
2  Satish   30      M

In [21]:
# calling the axis 
dict_name={'age':'AGE'}
df.rename(dict_name,axis=1)

    names  AGE Gender
0  Ramesh   10      M
1  Suresh   20      M
2  Satish   30      M

In [25]:
# calling the inplace 
dict_name={'age':'AGE'}
df.rename(columns=dict_name,inplace=True)
df

    names  AGE Gender
0  Ramesh   10      M
1  Suresh   20      M
2  Satish   30      M

In [ ]:
# can you change 2 to 'B'
# sir whats the diff btw labels and index sir ?
# index 0,1,2
# columns Names, Age, city

In [29]:
dict1={2:'b'}
df.rename(dict1)

    names  AGE Gender
0  Ramesh   10      M
1  Suresh   20      M
b  Satish   30      M

In [30]:
df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i*i for i in range(1,10)]
df1['cube_value']=[i*i*i for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [31]:
dir(df1)

SyntaxError: unmatched ')' (2944217322.py, line 1)

- len 

- columns

- shape

- dtypes

- head

- tail

In [32]:
len(df1)

9

In [33]:
df1.columns

Index(['value', 'square_value', 'cube_value'], dtype='object')

In [70]:
df1.shape

(9, 3)

In [34]:
df1.dtypes

value           int64
square_value    int64
cube_value      int64
dtype: object

In [35]:
df.dtypes

names     object
AGE        int64
Gender    object
dtype: object

In [36]:
df1.head()

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125

In [37]:
df1.tail()

   value  square_value  cube_value
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [80]:
df1.isnull()

   value  square_value  cube_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False

In [81]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         9 non-null      int64
 1   square_value  9 non-null      int64
 2   cube_value    9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

**Step-10 : How to change a specific value of a column**

In [ ]:
-df1.drop
    - either it will drop column or index

- df1.rename
    - either it will rename column or index

- df1.replace

In [38]:
df1.replace(to_replace=64,value=464)

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

**Step-11: Selection of a column**

In [40]:
df1['cube_value']
# series
# series looks like dataframe

0      1
1      8
2     27
3     64
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [41]:
type(df1)

pandas.core.frame.DataFrame

In [42]:
type(df1['cube_value'])
# 2D data

pandas.core.series.Series

In [44]:
df1['cube_value'].shape
# 1D data

(9,)

In [45]:
df1[['cube_value']]

   cube_value
0           1
1           8
2          27
3          64
4         125
5         216
6         343
7         512
8         729

In [46]:
type(df1[['cube_value']])
df1[['cube_value']].shape

(9, 1)

In [47]:
# square_value
# cube_value
# multiple always keep those in list
df1[['cube_value','square_value']]

   cube_value  square_value
0           1             1
1           8             4
2          27             9
3          64            16
4         125            25
5         216            36
6         343            49
7         512            64
8         729            81

**Step-12:How to append a row**

- loc

- iloc

In [38]:
df1.loc[rows,columns]
df1.iloc[rows,columns]
#we can select particular rows and coulmns using 

df1.iloc[3:7,1:3]
df1.loc[3:7,['square_value','cube_value']]
cols=['square_value','cube_value']
df1.loc[3:7,cols]

NameError: name 'df1' is not defined

In [1]:
df1.iloc[[2,3,4]]
df1.iloc[[2]]
df1.iloc[2]
df1.iloc[[2,3,4],[0,2]]
df1.iloc[2,0]
df1.iloc[:,0]
df1.iloc

NameError: name 'df1' is not defined